function budget_1(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;return sum;}
function budget_2(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_3(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_4(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_5(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_6(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_7(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_8(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_9(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_10(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_11(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_12(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_13(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_14(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_15(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_16(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_17(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_18(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_19(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_20(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_21(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_22(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_23(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_24(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_25(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_26(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_27(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_28(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_29(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_30(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_31(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_32(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_33(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_34(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_35(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_36(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_37(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_38(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_39(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
function budget_40(r){r.slot=1;local sum=0;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;sum+=r.count;r.slot=sum;return sum;}
local r={slot=0,count=3};
if(budget_1(r)!=3 || r.slot!=3) throw "cold budget value";
if(budget_2(r)!=6 || r.slot!=6) throw "cold budget value";
if(budget_3(r)!=9 || r.slot!=9) throw "cold budget value";
if(budget_4(r)!=12 || r.slot!=12) throw "cold budget value";
if(budget_5(r)!=15 || r.slot!=15) throw "cold budget value";
if(budget_6(r)!=18 || r.slot!=18) throw "cold budget value";
if(budget_7(r)!=21 || r.slot!=21) throw "cold budget value";
if(budget_8(r)!=24 || r.slot!=24) throw "cold budget value";
if(budget_9(r)!=27 || r.slot!=27) throw "cold budget value";
if(budget_10(r)!=30 || r.slot!=30) throw "cold budget value";
if(budget_11(r)!=33 || r.slot!=33) throw "cold budget value";
if(budget_12(r)!=36 || r.slot!=36) throw "cold budget value";
if(budget_13(r)!=39 || r.slot!=39) throw "cold budget value";
if(budget_14(r)!=42 || r.slot!=42) throw "cold budget value";
if(budget_15(r)!=45 || r.slot!=45) throw "cold budget value";
if(budget_16(r)!=48 || r.slot!=48) throw "cold budget value";
if(budget_17(r)!=51 || r.slot!=51) throw "cold budget value";
if(budget_18(r)!=54 || r.slot!=54) throw "cold budget value";
if(budget_19(r)!=57 || r.slot!=57) throw "cold budget value";
if(budget_20(r)!=60 || r.slot!=60) throw "cold budget value";
if(budget_21(r)!=63 || r.slot!=63) throw "cold budget value";
if(budget_22(r)!=66 || r.slot!=66) throw "cold budget value";
if(budget_23(r)!=69 || r.slot!=69) throw "cold budget value";
if(budget_24(r)!=72 || r.slot!=72) throw "cold budget value";
if(budget_25(r)!=75 || r.slot!=75) throw "cold budget value";
if(budget_26(r)!=78 || r.slot!=78) throw "cold budget value";
if(budget_27(r)!=81 || r.slot!=81) throw "cold budget value";
if(budget_28(r)!=84 || r.slot!=84) throw "cold budget value";
if(budget_29(r)!=87 || r.slot!=87) throw "cold budget value";
if(budget_30(r)!=90 || r.slot!=90) throw "cold budget value";
if(budget_31(r)!=93 || r.slot!=93) throw "cold budget value";
if(budget_32(r)!=96 || r.slot!=96) throw "cold budget value";
if(budget_33(r)!=99 || r.slot!=99) throw "cold budget value";
if(budget_34(r)!=102 || r.slot!=102) throw "cold budget value";
if(budget_35(r)!=105 || r.slot!=105) throw "cold budget value";
if(budget_36(r)!=108 || r.slot!=108) throw "cold budget value";
if(budget_37(r)!=111 || r.slot!=111) throw "cold budget value";
if(budget_38(r)!=114 || r.slot!=114) throw "cold budget value";
if(budget_39(r)!=117 || r.slot!=117) throw "cold budget value";
if(budget_40(r)!=120 || r.slot!=120) throw "cold budget value";
