#!/usr/bin/env python3
"""Generate editor grammars from the checked-in language vocabulary."""
import json
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent
WORDS = json.loads((ROOT / 'language-data.json').read_text())
NUMBER = r'\b0[xX][0-9a-fA-F]+\b|(?<![\w.])(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[eE][+-]?[0-9]+)?(?!\w)'
for language, data in WORDS.items():
    ident = 'sqgi-' + language
    scope = 'source.' + ident
    patterns = [
        {'name': 'comment.line.double-slash.' + ident, 'begin': '//|#', 'end': '$'},
        {'name': 'comment.block.' + ident, 'begin': r'/\*', 'end': r'\*/'},
        {'name': 'string.quoted.double.verbatim.' + ident, 'begin': '@"', 'end': '"(?!")',
         'patterns': [{'name': 'constant.character.escape.' + ident, 'match': '""'}]},
        {'name': 'string.quoted.double.' + ident, 'begin': '"', 'end': '"|$',
         'patterns': [{'name': 'constant.character.escape.' + ident, 'match': r'\\.'}]},
        {'name': 'string.quoted.single.' + ident, 'begin': "'", 'end': "'|$",
         'patterns': [{'name': 'constant.character.escape.' + ident, 'match': r'\\.'}]},
    ]
    kinds = {'keywords': 'keyword.control', 'types': 'storage.type',
             'constants': 'constant.language', 'builtins': 'support.function'}
    for kind, style in kinds.items():
        if data[kind]:
            patterns.append({'name': style + '.' + ident, 'match': r'\b(?:' + '|'.join(data[kind]) + r')\b'})
    patterns += [
        {'name': 'constant.numeric.' + ident, 'match': NUMBER},
        {'name': 'entity.name.function.' + ident, 'match': r'\b[A-Za-z_]\w*(?=\s*\()'},
        {'name': 'keyword.operator.' + ident, 'match': r'<=>|>>>|<-|::|[+*/%=!<>?&|^~\-]'},
    ]
    (ROOT / 'vscode/syntaxes' / (ident + '.tmLanguage.json')).write_text(json.dumps({
        'name': data['name'], 'scopeName': scope, 'patterns': patterns,
    }, indent=2) + '\n')
    xml = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<!-- Generated by editors/generate-languages.py. MIT; see LICENSE. -->',
           f'<language id="{ident}" name="{data["name"]}" version="2.0" _section="Source">',
           '  <metadata>', f'    <property name="globs">{data["glob"]}</property>',
           f'    <property name="mimetypes">text/x-{ident}</property>',
           '    <property name="line-comment-start">//</property>',
           '    <property name="block-comment-start">/*</property>',
           '    <property name="block-comment-end">*/</property>',
           '  </metadata>', '  <styles>']
    styles = {'comment': 'comment', 'string': 'string', 'escape': 'special-char',
              'keywords': 'keyword', 'types': 'type', 'constants': 'special-constant',
              'builtins': 'builtin', 'number': 'number', 'function': 'function', 'operator': 'operator'}
    for style, default in styles.items():
        xml.append(f'    <style id="{style}" name="{style.title()}" map-to="def:{default}"/>')
    xml += ['  </styles>', '  <definitions>',
            '    <context id="line-comment" style-ref="comment" end-at-line-end="true" class="comment">',
            '      <start>//|#</start>', '    </context>',
            '    <context id="block-comment" style-ref="comment" class="comment">',
            r'      <start>/\*</start><end>\*/</end>', '    </context>',
            '    <context id="escape" style-ref="escape"><match>\\\\.</match></context>',
            '    <context id="verbatim-escape" style-ref="escape"><match>""</match></context>',
            '    <context id="verbatim" style-ref="string" class="string">',
            '      <start>@"</start><end>"(?!")</end>',
            '      <include><context ref="verbatim-escape"/></include>', '    </context>']
    for kind, quote in [('string', '"'), ('character', "'")]:
        xml += [f'    <context id="{kind}" style-ref="string" end-at-line-end="true" class="string">',
                f'      <start>{quote}</start><end>{quote}</end>',
                '      <include><context ref="escape"/></include>', '    </context>']
    for kind in kinds:
        if not data[kind]:
            continue
        xml.append(f'    <context id="{kind}" style-ref="{kind}">')
        for keyword in data[kind]:
            xml.append(f'      <keyword>{keyword}</keyword>')
        xml.append('    </context>')
    xml += [f'    <context id="number" style-ref="number"><match>{escape(NUMBER)}</match></context>',
            r'    <context id="function" style-ref="function"><match>\b[A-Za-z_]\w*(?=\s*\()</match></context>',
            '    <context id="operator" style-ref="operator"><match>' + escape(r'<=>|>>>|<-|::|[+*/%=!<>?&|^~\-]') + '</match></context>',
            f'    <context id="{ident}" class="no-spell-check"><include>']
    for kind in ['line-comment', 'block-comment', 'verbatim', 'string', 'character', *kinds, 'number', 'function', 'operator']:
        if kind in kinds and not data[kind]:
            continue
        xml.append(f'      <context ref="{kind}"/>')
    xml += ['    </include></context>', '  </definitions>', '</language>', '']
    (ROOT / 'gtksourceview' / (ident + '.lang')).write_text('\n'.join(xml))
    vim_id = ident.replace('-', '_')
    vim = [
        '" Generated by editors/generate-languages.py. MIT; see LICENSE.',
        "if exists('b:current_syntax')", '  finish', 'endif',
        'syntax case match',
        r'syntax match sqgiFunction /\<[A-Za-z_]\w*\ze\s*(/',
        r'syntax match sqgiOperator /[+*\/%=!<>?&|^~:-]/',
        r'syntax match sqgiNumber /\<0[xX][0-9a-fA-F]\+\>/',
        r'syntax match sqgiNumber /\<\d\+\%(\.\d*\)\?\%([eE][+-]\?\d\+\)\?\>/',
        r'syntax match sqgiNumber /\%(\w\|\.\)\@<!\.\d\+\%([eE][+-]\?\d\+\)\?\>/',
    ]
    for kind, group in [('keywords', 'Keyword'), ('types', 'Type'),
                        ('constants', 'Constant'), ('builtins', 'Builtin')]:
        if data[kind]:
            vim.append('syntax keyword sqgi' + group + ' ' + ' '.join(data[kind]))
    vim += [
        r'syntax match sqgiEscape /\\./ contained',
        r'''syntax region sqgiString start=/"/ skip=/\\./ end=/"/ oneline contains=sqgiEscape,@Spell''',
        r"syntax region sqgiCharacter start=/'/ skip=/\\./ end=/'/ oneline contains=sqgiEscape",
        r'''syntax region sqgiVerbatim start=/@"/ skip=/""/ end=/"/ contains=@Spell''',
        r'syntax match sqgiComment /\/\/.*$/ contains=@Spell',
        r'syntax match sqgiComment /#.*$/ contains=@Spell',
        r'syntax region sqgiComment start=/\/\*/ end=/\*\// contains=@Spell',
        'syntax sync fromstart',
    ]
    for group, link in [('Function', 'Function'), ('Operator', 'Operator'),
                        ('Number', 'Number'), ('Keyword', 'Keyword'), ('Type', 'Type'),
                        ('Constant', 'Constant'), ('Builtin', 'Function'),
                        ('Escape', 'SpecialChar'), ('String', 'String'),
                        ('Character', 'Character'), ('Verbatim', 'String'), ('Comment', 'Comment')]:
        vim.append('highlight default link sqgi' + group + ' ' + link)
    vim += [f"let b:current_syntax = '{vim_id}'", '']
    (ROOT / 'vim/syntax' / (vim_id + '.vim')).write_text('\n'.join(vim))
