from pathlib import Path
import json,hashlib,shutil,ast,statistics
R=Path('/home/sam/Programming/sqgi');A=R/'devdocs/internals/jit-performance-iterations-2026-09-09';W=A/'constant-division-v30-work-in-progress';S=Path('/tmp/sqgi-constant-division-study')
h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
for p,v in json.loads((W/'applied-source-manifest.json').read_text()).items():assert h(R/p)==v,p
# Preserve the original six-group verifier. A distinct verifier records the
# intentionally incomplete pilot and applies all its checks to completed groups.
s=Path('/tmp/sqgi-v30-verify-pilots.py').read_text();s=s.replace("out={};expected_sha=", "out={};missing=[];expected_sha=")
s=s.replace("p=S/f'{suite}-pilot-w{w}.json';d=json.loads(p.read_text());", "p=S/f'{suite}-pilot-w{w}.json'\n  if not p.exists():missing.append(p.name);continue\n  d=json.loads(p.read_text());")
s=s.replace("'no_regressions_over_5pct':all", "'all_six_groups_complete':not missing,'missing_groups':missing,'stopped_at_user_request':True,'no_regressions_over_5pct':all")
s=s.replace("S/'pilot-verification.json'", "S/'partial-pilot-verification.json'")
s=s.replace("assert result['no_regressions_over_5pct'],'Investigate pilot regression before freezing'", "assert len(out)==4 and len(missing)==2\nassert result['no_regressions_over_5pct'],'Completed pilots contain a regression requiring investigation'")
ast.parse(s);Path('/tmp/sqgi-v30-verify-partial-pilots.py').write_text(s)
exec(compile(s,'/tmp/sqgi-v30-verify-partial-pilots.py','exec'),{'__name__':'__main__'})
for name in ['allocation-fault','tail-budget','emission-tier-probe','budget-preservation','buffer-probe']:
 shutil.copytree('/tmp/sqgi-v30-'+name,W/name,dirs_exist_ok=True)
shutil.copytree(S,W/'partial-study',dirs_exist_ok=True)
for p in Path('/tmp').glob('sqgi-v30-*.py'):shutil.copy2(p,W/p.name)
for p in Path('/tmp').glob('sqgi-v30-*.sh'):shutil.copy2(p,W/p.name)
for p in Path('/tmp').glob('sqgi-v30-*.log'):shutil.copy2(p,W/p.name)
shutil.copy2('/tmp/sqgi-freeze-v30.py',W/'sqgi-freeze-v30.py')
partial=json.loads((S/'partial-pilot-verification.json').read_text());rows={}
for name,row in partial['groups'].items():rows[name]={'paired_runtime_change_pct':(statistics.geometric_mean(v['paired_copies_ratio'] for v in row['copy_diagnostics'].values())-1)*100,'primary_comparison':row['geomean'],'regressions_over_5pct':row['regressions_over_5pct']}
status={'status':'stopped_at_user_request_commit_checkpoint','source_files':97,'binary_sha256':h(Path('/tmp/sqgi-v30-pilot/sqgi')),'engine_sha256':h(Path('/tmp/sqgi-scalar-leaf-20260909/libsqgi.so.1')),'pilot_session':68917,'pilot_terminal_exit_code':130,'completed_pilot_groups':rows,'incomplete_pilot_groups':partial['missing_groups'],'v30_full_performance_acceptance':False,'latest_accepted_version':'V29','goal_targets_met':False,'matched_pgo_lto_done':False,'retry_gap':'Existing private proto/loop permanent resource rejection reproduced unchanged in V29/V30; not repaired.'}
(W/'application-status.json').write_text(json.dumps(status,indent=2)+'\n')
text='''# V30 checkpoint — stopped at user request\n\nThe user requested ending optimization work and committing/pushing the current\nwork on 2026-09-10. Pilot session 68917 was interrupted and returned exit130.\nNo optimization, test, profile or timing process remains running.\n\nV29 remains the latest accepted full56 result: 1.882226095x audit,\nNode 8.119330 / p90 23.761645, GJS 5.370798 / p90 12.629266.\nThe target and first milestone are not achieved. Matched PGO/LTO is outstanding.\n\nCurrent source includes the V30 positive constant-divisor experiment in all\nthree AArch64 compiler paths. It is correctness-validated, not performance-accepted.\nAll four 100-test runs and two 41-holdout runs passed; 16 native groups executed.\nEight x64 tests retain the same 32 known member assertions. Original 13 allocation\ncases, 24 tail fixtures, 16 old budget layouts, six native captures and 1244 buffer\nhelpers passed. New 48 paired budget fixtures, 14 installation reference/fault\ncases and six copied-constant fixtures across reference/release/strict sanitizer\nbuilds passed. Source manifest has 97 files.\n\nTwenty-four repeated-call reference/fault cases expose an unchanged retry gap:\nprecise functions retry on the next call; private proto/loop cache executable\nallocation failure and remain interpreted across three calls. Results and prefix\neffects remain correct. This gap is recorded, not repaired.\n\nFour of six pilot groups completed with five rotating rounds, repeated copies\nof both versions and interpreter checksum references. No completed group has a\nprimary-comparison regression over 5%. Paired runtime changes versus V29:\n\n'''
for name,row in rows.items():text+=f"- {name}: {row['paired_runtime_change_pct']:+.3f}%.\n"
text+='''\nWarmup4 members was interrupted; warmup4 owners did not run. Their absence is\nexplicitly recorded in partial-study/partial-pilot-verification.json; the original\nsix-group verification requirement is retained in sqgi-v30-verify-pilots.py.\nThe two calibration cases in warmup5 members regressed about 2.3–2.6%.\nNo V30 full56, both-seed application controls, profitability or seven fresh\nprofiles were collected. Do not infer an overall V30 improvement.\n\nThe partial study, raw logs, probe evidence and prepared study scripts are saved\nhere. Prepared freeze/full-study/capture scripts have not been executed; changed\nsecondary native captures still require arithmetic-diff review before acceptance.\nA future restart must explicitly choose how to continue the incomplete pilot\nwithout overwriting the preserved results. All frozen older evidence is retained.\n'''
(W/'continuation.md').write_text(text);(W/'README.md').write_text(text)
p=R/'devdocs/internals/jit-performance-iterations-2026-09-09.md';s=p.read_text();a=s.index('## V30: signed constant division, full correctness in progress')
s=s[:a]+'''## V30: signed constant division — stopped before performance acceptance\n\nThe current source includes positive constant-divisor lowering in all three\nAArch64 compiler paths, with signed semantics and old-layout code-budget fallback.\nAll four 100-test runs, both 41-holdout runs, 16 native groups, strict sanitizer\nchecks and the eight-test x64 comparison passed their recorded gates (x64 retains\nthe same 32 known member assertions). Constant proofs, 48 paired budget fixtures,\n14 installation cases and the original resource/lifetime checks are preserved.\n\nThe user requested stopping and committing on 2026-09-10. Four pilot groups\ncompleted; warmup4 members was interrupted and warmup4 owners was not run.\nV30 has no full56 result and is not performance-accepted. The completed warmup5\nmethods/owners groups were nearly flat, while members regressed 0.72% in aggregate\nand calibration cases regressed about 2.3–2.6%. Repeated-call fault probes also\nconfirmed an existing private proto/loop allocation-failure retry gap, unchanged\nfrom V29. Neither the performance targets nor matched PGO/LTO are complete.\n\n[V30 checkpoint and partial evidence](jit-performance-iterations-2026-09-09/constant-division-v30-work-in-progress/README.md).\nV29 remains the latest accepted full performance result.\n'''
p.write_text(s)
shutil.copy2('/tmp/sqgi-stop-checkpoint-20260910.py',W/'save-stop-checkpoint.py')
(W/'stop-checkpoint-sha256.json').write_text(json.dumps({str(p.relative_to(W)):h(p) for p in sorted(W.rglob('*')) if p.is_file() and p.name!='stop-checkpoint-sha256.json'},indent=2)+'\n')
print('STOP_CHECKPOINT_SAVED',len(rows),'completed pilot groups; source97 verified; no performance acceptance claimed')
