" Generated by editors/generate-languages.py. MIT; see LICENSE.
if exists('b:current_syntax')
  finish
endif
syntax case match
syntax match sqgiFunction /\<[A-Za-z_]\w*\ze\s*(/
syntax match sqgiOperator /[+*\/%=!<>?&|^~:-]/
syntax match sqgiNumber /\<0[xX][0-9a-fA-F]\+\>/
syntax match sqgiNumber /\<\d\+\%(\.\d*\)\?\%([eE][+-]\?\d\+\)\?\>/
syntax match sqgiNumber /\%(\w\|\.\)\@<!\.\d\+\%([eE][+-]\?\d\+\)\?\>/
syntax keyword sqgiKeyword while do if else break continue return function local for foreach in typeof base delete try catch throw clone yield resume switch case default this class extends constructor instanceof static enum const async await rawcall
syntax keyword sqgiConstant true false null __LINE__ __FILE__
syntax keyword sqgiBuiltin import print format sqgi Task
syntax match sqgiEscape /\\./ contained
syntax region sqgiString start=/"/ skip=/\\./ end=/"/ oneline contains=sqgiEscape,@Spell
syntax region sqgiCharacter start=/'/ skip=/\\./ end=/'/ oneline contains=sqgiEscape
syntax region sqgiVerbatim start=/@"/ skip=/""/ end=/"/ contains=@Spell
syntax match sqgiComment /\/\/.*$/ contains=@Spell
syntax match sqgiComment /#.*$/ contains=@Spell
syntax region sqgiComment start=/\/\*/ end=/\*\// contains=@Spell
syntax sync fromstart
highlight default link sqgiFunction Function
highlight default link sqgiOperator Operator
highlight default link sqgiNumber Number
highlight default link sqgiKeyword Keyword
highlight default link sqgiType Type
highlight default link sqgiConstant Constant
highlight default link sqgiBuiltin Function
highlight default link sqgiEscape SpecialChar
highlight default link sqgiString String
highlight default link sqgiCharacter Character
highlight default link sqgiVerbatim String
highlight default link sqgiComment Comment
let b:current_syntax = 'sqgi_squirrel'
