" Generated by editors/generate-languages.py. MIT; see LICENSE.
if exists('b:current_syntax')
  finish
endif
syntax case match
syntax match sqgiFunction /\<[A-Za-z_]\w*\ze\s*(/
syntax match sqgiOperator /[+*\/%=!<>?&|^~:-]/
syntax match sqgiNumber /\<0[xX][0-9a-fA-F]\+\>/
syntax match sqgiNumber /\<\d\+\%(\.\d*\)\?\%([eE][+-]\?\d\+\)\?\>/
syntax match sqgiNumber /\%(\w\|\.\)\@<!\.\d\+\%([eE][+-]\?\d\+\)\?\>/
syntax keyword sqgiKeyword export struct class in inout if else for while return require
syntax keyword sqgiType i64 f64 bool void
syntax keyword sqgiConstant true false
syntax keyword sqgiBuiltin abs acos acosh asin asinh atan atan2 atanh cbrt ceil copysign cos cosh erf erfc exp exp2 expm1 fabs floor fmax fmin fmod hypot isfinite isinf isnan lgamma log log10 log1p log2 pow remainder round signbit sin sinh sqrt tan tanh tgamma trunc
syntax match sqgiEscape /\\./ contained
syntax region sqgiString start=/"/ skip=/\\./ end=/"/ oneline contains=sqgiEscape,@Spell
syntax region sqgiCharacter start=/'/ skip=/\\./ end=/'/ oneline contains=sqgiEscape
syntax region sqgiVerbatim start=/@"/ skip=/""/ end=/"/ contains=@Spell
syntax match sqgiComment /\/\/.*$/ contains=@Spell
syntax match sqgiComment /#.*$/ contains=@Spell
syntax region sqgiComment start=/\/\*/ end=/\*\// contains=@Spell
syntax sync fromstart
highlight default link sqgiFunction Function
highlight default link sqgiOperator Operator
highlight default link sqgiNumber Number
highlight default link sqgiKeyword Keyword
highlight default link sqgiType Type
highlight default link sqgiConstant Constant
highlight default link sqgiBuiltin Function
highlight default link sqgiEscape SpecialChar
highlight default link sqgiString String
highlight default link sqgiCharacter Character
highlight default link sqgiVerbatim String
highlight default link sqgiComment Comment
let b:current_syntax = 'sqgi_kernel'
