function budget_1(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;}return sum;}
function budget_2(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;}return sum;}
function budget_3(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_4(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_5(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_6(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_7(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_8(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_9(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_10(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_11(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_12(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_13(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_14(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_15(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_16(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_17(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_18(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_19(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_20(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_21(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_22(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_23(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_24(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_25(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_26(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_27(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_28(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_29(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_30(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_31(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_32(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_33(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_34(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_35(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_36(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_37(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_38(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_39(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_40(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_41(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_42(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_43(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_44(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_45(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_46(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_47(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_48(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_49(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_50(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_51(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_52(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_53(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_54(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_55(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_56(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_57(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_58(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_59(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_60(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_61(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_62(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_63(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_64(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_65(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_66(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_67(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_68(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_69(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_70(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_71(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_72(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_73(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_74(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_75(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_76(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_77(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_78(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_79(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
function budget_80(r,n) { local sum=0;for(local i=0;i<n;i++){r.slot=i;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;sum+=r.count;}return sum;}
local r={slot=0,count=3};
if(budget_1(r,3)!=9 || r.slot!=2) throw "budget value";
if(budget_2(r,3)!=18 || r.slot!=2) throw "budget value";
if(budget_3(r,3)!=27 || r.slot!=2) throw "budget value";
if(budget_4(r,3)!=36 || r.slot!=2) throw "budget value";
if(budget_5(r,3)!=45 || r.slot!=2) throw "budget value";
if(budget_6(r,3)!=54 || r.slot!=2) throw "budget value";
if(budget_7(r,3)!=63 || r.slot!=2) throw "budget value";
if(budget_8(r,3)!=72 || r.slot!=2) throw "budget value";
if(budget_9(r,3)!=81 || r.slot!=2) throw "budget value";
if(budget_10(r,3)!=90 || r.slot!=2) throw "budget value";
if(budget_11(r,3)!=99 || r.slot!=2) throw "budget value";
if(budget_12(r,3)!=108 || r.slot!=2) throw "budget value";
if(budget_13(r,3)!=117 || r.slot!=2) throw "budget value";
if(budget_14(r,3)!=126 || r.slot!=2) throw "budget value";
if(budget_15(r,3)!=135 || r.slot!=2) throw "budget value";
if(budget_16(r,3)!=144 || r.slot!=2) throw "budget value";
if(budget_17(r,3)!=153 || r.slot!=2) throw "budget value";
if(budget_18(r,3)!=162 || r.slot!=2) throw "budget value";
if(budget_19(r,3)!=171 || r.slot!=2) throw "budget value";
if(budget_20(r,3)!=180 || r.slot!=2) throw "budget value";
if(budget_21(r,3)!=189 || r.slot!=2) throw "budget value";
if(budget_22(r,3)!=198 || r.slot!=2) throw "budget value";
if(budget_23(r,3)!=207 || r.slot!=2) throw "budget value";
if(budget_24(r,3)!=216 || r.slot!=2) throw "budget value";
if(budget_25(r,3)!=225 || r.slot!=2) throw "budget value";
if(budget_26(r,3)!=234 || r.slot!=2) throw "budget value";
if(budget_27(r,3)!=243 || r.slot!=2) throw "budget value";
if(budget_28(r,3)!=252 || r.slot!=2) throw "budget value";
if(budget_29(r,3)!=261 || r.slot!=2) throw "budget value";
if(budget_30(r,3)!=270 || r.slot!=2) throw "budget value";
if(budget_31(r,3)!=279 || r.slot!=2) throw "budget value";
if(budget_32(r,3)!=288 || r.slot!=2) throw "budget value";
if(budget_33(r,3)!=297 || r.slot!=2) throw "budget value";
if(budget_34(r,3)!=306 || r.slot!=2) throw "budget value";
if(budget_35(r,3)!=315 || r.slot!=2) throw "budget value";
if(budget_36(r,3)!=324 || r.slot!=2) throw "budget value";
if(budget_37(r,3)!=333 || r.slot!=2) throw "budget value";
if(budget_38(r,3)!=342 || r.slot!=2) throw "budget value";
if(budget_39(r,3)!=351 || r.slot!=2) throw "budget value";
if(budget_40(r,3)!=360 || r.slot!=2) throw "budget value";
if(budget_41(r,3)!=369 || r.slot!=2) throw "budget value";
if(budget_42(r,3)!=378 || r.slot!=2) throw "budget value";
if(budget_43(r,3)!=387 || r.slot!=2) throw "budget value";
if(budget_44(r,3)!=396 || r.slot!=2) throw "budget value";
if(budget_45(r,3)!=405 || r.slot!=2) throw "budget value";
if(budget_46(r,3)!=414 || r.slot!=2) throw "budget value";
if(budget_47(r,3)!=423 || r.slot!=2) throw "budget value";
if(budget_48(r,3)!=432 || r.slot!=2) throw "budget value";
if(budget_49(r,3)!=441 || r.slot!=2) throw "budget value";
if(budget_50(r,3)!=450 || r.slot!=2) throw "budget value";
if(budget_51(r,3)!=459 || r.slot!=2) throw "budget value";
if(budget_52(r,3)!=468 || r.slot!=2) throw "budget value";
if(budget_53(r,3)!=477 || r.slot!=2) throw "budget value";
if(budget_54(r,3)!=486 || r.slot!=2) throw "budget value";
if(budget_55(r,3)!=495 || r.slot!=2) throw "budget value";
if(budget_56(r,3)!=504 || r.slot!=2) throw "budget value";
if(budget_57(r,3)!=513 || r.slot!=2) throw "budget value";
if(budget_58(r,3)!=522 || r.slot!=2) throw "budget value";
if(budget_59(r,3)!=531 || r.slot!=2) throw "budget value";
if(budget_60(r,3)!=540 || r.slot!=2) throw "budget value";
if(budget_61(r,3)!=549 || r.slot!=2) throw "budget value";
if(budget_62(r,3)!=558 || r.slot!=2) throw "budget value";
if(budget_63(r,3)!=567 || r.slot!=2) throw "budget value";
if(budget_64(r,3)!=576 || r.slot!=2) throw "budget value";
if(budget_65(r,3)!=585 || r.slot!=2) throw "budget value";
if(budget_66(r,3)!=594 || r.slot!=2) throw "budget value";
if(budget_67(r,3)!=603 || r.slot!=2) throw "budget value";
if(budget_68(r,3)!=612 || r.slot!=2) throw "budget value";
if(budget_69(r,3)!=621 || r.slot!=2) throw "budget value";
if(budget_70(r,3)!=630 || r.slot!=2) throw "budget value";
if(budget_71(r,3)!=639 || r.slot!=2) throw "budget value";
if(budget_72(r,3)!=648 || r.slot!=2) throw "budget value";
if(budget_73(r,3)!=657 || r.slot!=2) throw "budget value";
if(budget_74(r,3)!=666 || r.slot!=2) throw "budget value";
if(budget_75(r,3)!=675 || r.slot!=2) throw "budget value";
if(budget_76(r,3)!=684 || r.slot!=2) throw "budget value";
if(budget_77(r,3)!=693 || r.slot!=2) throw "budget value";
if(budget_78(r,3)!=702 || r.slot!=2) throw "budget value";
if(budget_79(r,3)!=711 || r.slot!=2) throw "budget value";
if(budget_80(r,3)!=720 || r.slot!=2) throw "budget value";
