from pathlib import Path
import json,hashlib,shutil,collections
R=Path('/home/sam/Programming/sqgi');A=R/'devdocs/internals/jit-performance-iterations-2026-09-09';D=A/'shared-helper-v28-work-in-progress';P=A/'cold-literal-lookup-v27'
h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
for mode in ['release','asan']:
 for enabled in ['enabled','default']:
  assert '100% tests passed, 0 tests failed out of 100' in Path(f'/tmp/sqgi-v28-{mode}-{enabled}-tests.log').read_text()
  detail=Path(f'/tmp/sqgi-v28-{mode}-{enabled}-ctest-detail.log').read_text()
  assert '[coverage] executed 15 AArch64 generated-code groups' in detail
  assert '[coverage] executed AArch64 shared precise helper contracts' in detail
 binary=Path('/tmp/sqgi-scalar-leaf-20260909/sqgi' if mode=='release' else '/tmp/sqgi-leaf-asan-strict-20260909.M32jMl/sqgi')
 d=json.loads(Path(f'/tmp/sqgi-v28-{mode}-holdouts/results.json').read_text());assert d['sha256']==h(binary)
 assert sum(len(rows[0]['rows']) for rows in d['suites'].values())==41
fails=lambda p:collections.Counter(x.strip() for x in p.read_text().splitlines() if x.startswith('FAIL:'))
a=fails(P/'sqgi-v27-x64-tests.log');b=fails(Path('/tmp/sqgi-v28-x64-tests.log'));assert a==b and sum(b.values())==32
manifest=json.loads((D/'applied-source-manifest.json').read_text());assert len(manifest)==96
for path,want in manifest.items():assert h(R/path)==want,path
for path,want in json.loads((P/'unchanged-benchmarks-and-scripts.json').read_text()).items():assert h(R/path)==want,path
for probe in ['allocation-fault','tail-budget','buffer-probe','budget-preservation']:
 p=Path('/tmp/sqgi-v28-'+probe);v=json.loads((p/'verification.json').read_text());assert v['verified']
 assert v['engine_sha256']==h(Path('/tmp/sqgi-scalar-leaf-20260909/libsqgi.so.1'))
 shutil.copytree(p,D/probe,dirs_exist_ok=True)
for p in Path('/tmp').glob('sqgi-v28-*.log'):shutil.copy2(p,D/p.name)
for mode in ['release','asan']:shutil.copytree(Path(f'/tmp/sqgi-v28-{mode}-holdouts'),D/f'{mode}-holdouts',dirs_exist_ok=True)
for name in ['verify-tail.py','verify-probes.py','run-faults.sh','prepare-buffer-symbols.py','pilot-timings.sh','verify-pilots.py']:
 shutil.copy2(Path('/tmp/sqgi-v28-'+name),D/('sqgi-v28-'+name))
s=json.loads((D/'application-status.json').read_text());s.pop('remaining_gates_session',None);s.update(correctness_gates_complete=True,tail_budget_verified=True,allocation_cases=11,budget_layouts_preserved=16,buffer_helpers_before=1772,buffer_helpers_after=1244,timings_started=True,timing_session=5779)
(D/'application-status.json').write_text(json.dumps(s,indent=2)+'\n')
(D/'remaining-gates-verification.json').write_text(json.dumps(dict(verified=True,source_files=96,unchanged_benchmarks_and_scripts=88,release_and_sanitizer_test_runs=4,tests_per_run=100,holdout_cases_per_build=41,x64_known_assertions=32,native_groups=15,binary_sha256=h(Path('/tmp/sqgi-scalar-leaf-20260909/sqgi'))),indent=2)+'\n')
(D/'README.md').write_text('''# V28 shared helper setup — measurement in progress

Shared helper-call setup lets buffer rotation retain tier3 native member reads
within the existing 8192-byte budget. Actual unchanged buffer traces show four
successful native returns on both versions: checked helper calls fall from1772
to1244 (GETK464→8; GET76→4). Generated bytes fall from7884 to7408.
The other five canonical captures retain the exact pointer-normalized V27 code.

All four100-test release/sanitizer runs and both41-case holdout sets pass;
15native groups execute; x64 retains the same32known assertions. Eleven resource
probes cover failure/retry including shared rich code. All16previous boundary
layouts remain pointer-normalized equal.24tail-budget fixtures execute natively;
20observed tail-only overflow attempts retry lower tiers successfully. The exact
8192/8196-byte boundary is covered. Diagnostics retain the initial GDB symbol
lookup failure and subsequent mangled-symbol correction.

Five-round rotating pilots compare V27, V28, an identical V28 repeat, and Node,
with interpreter checksum references and both4/5warmups. No V28 performance
claim is accepted yet. V27 remains the latest accepted full56 result.
''')
print('V28 correctness/probe evidence archived; pilot measurements active')
